### PR TITLE
Finish test android

### PR DESCRIPTION
**Pull request by juleimisf**
Project under the MVVM, using libraries like Retrofit for the consumption of APIS, Kotlin programming language, testing with Robolectric and more.

### CODE REVIEW

**Comment by cs-davi-silva** [comment]
Hello @juleimisf 
Thank you for submitting the challenge! 😃 

I'm trying to take a look at your challenge but I think you did not commit some files in root of your repository, like the `build.gradle` and `settings.gradle`.

Can you fix this?

**Comment by juleimisf** [comment]
Oh thanks for letting me know. I'll do it sometime today. Have a nice day!

**Comment by juleimisf** [comment]
add news files for gradle

**Comment by juleimisf** [comment]
Hi Davi! Ive fixed the graddle issue in a new commit, now it should work properly. Thanks! If you have any issue please let me know!

**Pull request closed without merging**
